POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "John Doe Testing",
  "email": "fdafadffadfe.com@gmail.com",
  "address": "123 Street",
  "dateOfBirth": "1992-04-02",
  "registeredDate": "2026-02-02"
}